let productos=[
    {
        codigo:1,
        descripcion:"producto1",
        nombre:"nombre1",
        precio:8000,
    },
    {
        codigo:2,
        descripcion:"producto2",
        nombre:"nombre2",
        precio:8000,
    },
    {
        codigo:3,
        descripcion:"producto3",
        nombre:"nombre3",
        precio:8000,
    },
]
console.log(productos)